---
title: "Data Normalization"
author: "Helen Moses"
date: "2026-03-24"
output: pdf_document
---

```{r}
# load necessary packages
library(tidyverse)
```

```{r}
# load un-normalized data 
movie <- read_csv("movie.csv")
colnames(movie)
```

```{r}
# movies table
movies <- movie[,c("id", "title", "original_title", "imdb_id", "release_date",
                   "runtime", "budget", "revenue", "overview", "tagline", 
                   "homepage", "poster_path", "backdrop_path")]

#save table as csv
#write_csv(movies, "movies.csv")
```

```{r}
# ratings table
ratings <- movie |>
  select(id = id,
         movie_id = id,
         popularity,
         vote_count,
         vote_average)

#save table as csv
#write_csv(ratings, "ratings.csv")
```

```{r}
# genres table
genres <- movie |>
  select(id, genres)

genres <- genres |>
  separate_rows(genres, sep = ",\\s*")

name <- unique(genres$genres)
id <- 1:length(name)
description <- c("serious stories that focus on character-driven narratives",
                 "wholesome stories that apeal to all ages",
                 "stories often including dangerous journeys or quests",
                 "non-fiction stories",
                 "stories about war, usually based on true events",
                 "funny stories designed to make people laugh",
                 "love stories that focus on character-driven narratives",
                 "adventure stories that contain unrelalistic aspects",
                 "fast paced stories usually envolving danger",
                 "stories that typically elicit high levels of suspense",
                 "stories characterized by supernatural elements",
                 "scary stories that elicit fear",
                 "stories that revolve around somethign unknown",
                 "stories that incorporate songs and dance",
                 "hisorical stories that are usuaally based on true events",
                 "stories revolving around illicit activites",
                 "stories told by frame to frame capturing",
                 "stories typically surrounding 19th centrury cowboys")

genres <- as.data.frame(cbind(id, name, description))

#write_csv(genres, "genres.csv")
```

```{r}
#movies_genres_table
movies_genres <- movie |>
  select(movies_id = id, 
         name = genres)

movies_genres <- movies_genres |>
  separate_rows(name, sep = ",\\s*")

temp <- genres |>
  select(genres_id = id,
         name)

movies_genres <- left_join(movies_genres, temp, by = join_by(name))
movies_genres$id <- 1:nrow(movies_genres)

movies_genres <- movies_genres |>
  select(id, movies_id, genres_id)

#write_csv(movies_genres, "movies_genres.csv")
```

```{r}
# languages_table
languages <- movie |>
  select(id, spoken_languages)

languages <- languages |>
  separate_rows(spoken_languages, sep = ",\\s*")

language <- unique(languages$spoken_languages)
id <- 1:length(language)

languages <- as.data.frame(cbind(id, language))

#write_csv(languages, "languages.csv")
```

